string SWITCH_TO_ACTION = switch-to-action
string SELECT_ACTION_STEP = select-action-step
string SELECT_ARM_STEP = select-arm-step
string DESELECT_ARM_STEP = deselect-arm-step
string DELETE_STEP = delete-step
string DELETE_ARM_STEP = delete-arm-step
string SET_LOOP_STEP = set-loop-step
string SET_NO_LOOP_STEP = set-no-loop-step
string SET_STRATEGY = set-strategy
string SET_IGNORE_CONDITIONS = set-ignore-conditions
string SET_NO_IGNORE_CONDITIONS = set-no-ignore-conditions
string command
uint8 param